/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpRadioBtn {
        "radioOptions": string;
    }
}
declare global {
    interface HTMLIpRadioBtnElement extends Components.IpRadioBtn, HTMLStencilElement {
    }
    var HTMLIpRadioBtnElement: {
        prototype: HTMLIpRadioBtnElement;
        new (): HTMLIpRadioBtnElement;
    };
    interface HTMLElementTagNameMap {
        "ip-radio-btn": HTMLIpRadioBtnElement;
    }
}
declare namespace LocalJSX {
    interface IpRadioBtn {
        "radioOptions"?: string;
    }
    interface IntrinsicElements {
        "ip-radio-btn": IpRadioBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-radio-btn": LocalJSX.IpRadioBtn & JSXBase.HTMLAttributes<HTMLIpRadioBtnElement>;
        }
    }
}
